
### FORWARD PROPAGATION, BACK PROPAGATION

In [56]:
import numpy as np 
learning_rate = 0.01

In [52]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [93]:
def derivatives_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))

### Step 0: Read input and output

In [ ]:
X = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
Y = np.array([[1],[1],[0]])
print (X)
print (Y)

### Step 1: Initialize weights and biases with random values

In [95]:
np.random.seed(14)
wh=np.random.rand(4,3)
wh=np.round(wh,decimals=2)
bh=np.random.rand(1,3)
bh=np.round(bh,decimals=2)
wout=np.random.rand(3,1)
wout=np.round(wout,decimals=2)
bout=np.random.rand(1,1)
bout=np.round(bout,decimals=2)
print (wh)

[[0.51 0.77 0.87]
 [0.01 0.31 0.96]
 [0.51 0.32 0.54]
 [0.22 0.81 0.34]]


In [96]:
print (bh)

[[0.54 0.01 0.67]]


In [97]:
print (wout)

[[0.21]
 [0.93]
 [0.37]]


In [98]:
print (bout)

[[0.75]]


### Step 2: Calculate hidden layer input

In [99]:
hidden_layer_input=np.dot(X,wh) + bh
print (hidden_layer_input)

[[1.56 1.1  2.08]
 [1.78 1.91 2.42]
 [0.77 1.13 1.97]]


### Step 3: Perform non-linear transformation on hidden linear input

In [100]:
hiddenlayer_activations = sigmoid(hidden_layer_input)
print (hiddenlayer_activations)

[[0.82635335 0.75026011 0.88894403]
 [0.85569687 0.87101915 0.91833974]
 [0.68352089 0.7558389  0.87761111]]


### Step 4: Perform linear and non-linear transformation of hidden layer activation at output layer

In [101]:
output_layer_input = np.dot(hiddenlayer_activations,wout) + bout
print (hiddenlayer_activations)

[[0.82635335 0.75026011 0.88894403]
 [0.85569687 0.87101915 0.91833974]
 [0.68352089 0.7558389  0.87761111]]


In [102]:
output = sigmoid(output_layer_input)
print (output)

[[0.87546686]
 [0.88889761]
 [0.87227059]]


### Step 5: Calculate gradient of Error(E) at output layer

In [103]:
E = Y - output
print (E)

[[ 0.12453314]
 [ 0.11110239]
 [-0.87227059]]


### Step 6: Compute slope at output and hidden layer

In [104]:
slope_output_layer= derivatives_sigmoid(output)
print (slope_output_layer)

[[0.20761262]
 [0.20645991]
 [0.2078856 ]]


In [105]:
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print (slope_hidden_layer)

[[0.21174717 0.21787468 0.20645591]
 [0.20929257 0.20799233 0.20390232]
 [0.22293183 0.21743793 0.20742919]]


### Step 7: Compute delta at output layer

In [106]:
lr = 1
d_output = E * slope_output_layer*lr
print (d_output)


[[ 0.02585465]
 [ 0.02293819]
 [-0.18133249]]


### Step 8: Calculate Error at hidden layer

In [107]:
Error_at_hidden_layer = np.dot(d_output, wout.T)
print (Error_at_hidden_layer)

[[ 0.00542948  0.02404483  0.00956622]
 [ 0.00481702  0.02133252  0.00848713]
 [-0.03807982 -0.16863922 -0.06709302]]


### Step 9: Compute delta at hidden layer

In [108]:
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print (d_hiddenlayer)

[[ 0.00114968  0.00523876  0.001975  ]
 [ 0.00100817  0.004437    0.00173055]
 [-0.0084892  -0.03666856 -0.01391705]]


### Step 10: Update weight at both output and hidden layer

In [109]:
wout = wout + np.dot(hiddenlayer_activations, d_output) * learning_rate
print (wout)


[[0.2087738 ]
 [0.92875579]
 [0.3687587 ]]


In [110]:
wh = wh+ np.dot(X.T,d_hiddenlayer) * learning_rate
print (wh)

[[0.51002158 0.77009676 0.87003706]
 [0.00991511 0.30963331 0.95986083]
 [0.51002158 0.32009676 0.54003706]
 [0.21992519 0.80967768 0.33987813]]


### Step 11: Update biases at both output and hidden layer

In [111]:
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate
print (bh)

[[0.53993669 0.00973007 0.66989788]]


In [112]:
bout = bout + np.sum(d_output, axis=0)*learning_rate
print (bout)

[[0.7486746]]
